### ISSUE TITLE
Can I get a license to update and use this?

### ISSUE THREAD

**Issue by Greg-Boggs** [NYPL/nypl-bibliophpile#6]
It appears that the intention is to open source this bibliocommons library. I'd like to publish a few updates and use this to connect our library's website here in Portland to Bibliocommons, but I noticed there's no license on this software which I believe means the software is all rights reserved and not available for my use. 

Would someone be willing to add a license they deem appropriate? I noticed other repos in your organization were licensed Apache for example.

**Comment by mwbenowitz** [comment]
@Greg-Boggs Thanks for reaching out. We are happy to apply the standard Apache 2.0 license to this repo, you should see that happen sometime early next week.

**Comment by Greg-Boggs** [comment]
That's awesome!

**Comment by mwbenowitz** [comment]
This should be addressed by PR #7!

**Comment by Greg-Boggs** [comment]
Thanks y'all are awesome. I should figure out a way to collaborate with your newer code repos.

 I made a few minor tweaks in my fork like putting the license key into composer.json. I'm guessing since y'all don't use biblio anymore, you probably aren't worried about this repo, but if you want me to send updates back, let me know.

~G
